name: npm audit

env:
  BACK_PATH: back
  FRONT_PATH: webtsx

on:
  push:
    branches: ['main', 'develop']
    paths:
      - "**/package.json"
      - "**/package-lock.json"
  pull_request:
    paths:
      - "**/package.json"
      - "**/package-lock.json"
  workflow_dispatch:

jobs:
  audit-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Audit backend
        working-directory: ${{ env.BACK_PATH }}
        run: |
          npm audit --audit-level=high --omit=dev

  audit-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Audit frontend
        working-directory: ${{ env.FRONT_PATH }}
        run: |
          npm audit --audit-level=high --omit=dev

  notify-backend:
    runs-on: ubuntu-latest
    if: |
      failure()
    needs: [audit-backend]
    name: Notify audit failure
    steps:
      - name: Send telegram message on audit fail
        uses: appleboy/telegram-action@master
        with:
          to: ${{ vars.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            Проект: ${{ vars.PROJECT_NAME }}
            ❌ Audit backend не удался!
            Проверьте логи workflow: ${{ gitea.server_url }}/${{ gitea.repository }}/actions

  notify-frontend:
    runs-on: ubuntu-latest
    if: |
      failure()
    needs: [audit-frontend]
    name: Notify audit failure
    steps:
      - name: Send telegram message on audit fail
        uses: appleboy/telegram-action@master
        with:
          to: ${{ vars.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            Проект: ${{ vars.PROJECT_NAME }}
            ❌ Audit frontend не удался!
            Проверьте логи workflow: ${{ gitea.server_url }}/${{ gitea.repository }}/actions